### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-team-pro#1]
[diagrama de clases.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-team-pro/files/7823759/diagrama.de.clases.pdf)

**Comment by Edwin38H** [comment]
calificación: 29
-falto imagen y 1 linea de conclusión

**Comment by josealfredo79** [comment]
En el diagrama de clases en los métodos GenerarCita, Mostrar,  Pagar, hay que agregar los pase de parámetros

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
